POST http://localhost:5000/users
Content-Type: application/json

{
  "email": "superman3-k@hotmail.fr",
  "password": "superman",
  "role": "ADMIN"
}

###
GET http://localhost:5000/users?email=superman-k@hotmail.fr

###
GET http://localhost:5000/users/1

###
PUT http://localhost:5000/users/1
Content-Type: application/json

{
  "email": "admin@test.fr",
  "password": "adkjhkjhkjhmklkin",
  "role": "ADMINN"
}

###
POST http://localhost:5000/transactions
Content-Type: application/json

{
  
  "status": "ENCOURS",
  "price": 15.00,
  "MerchantId" : 3
}

###
GET http://localhost:5000/transactions?createdAt=2020-07-12

###
GET http://localhost:5000/transactions/1

###
GET http://localhost:5000/transactions/stats?merchantId=1

###
GET http://localhost:5000/transactions/stats/date

###
PUT http://localhost:5000/transactions/1
Content-Type: application/json

{
  "status": "TERMINER",
  "price": "10"
}

###
PUT http://localhost:5000/secure/transactions/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfdG9rZW4iOiJ0ZXN0X2NsaWVudF90b2tlbiIsImlhdCI6MTU5NDU2MzEyOCwiZXhwIjoxNTk0NTY2NzI4fQ.IQtF7vmnm6gkiFctZOb-awL_zdtvn5xvVjMU7m-UeFI
Content-Type: application/json

{
  "status": "ENCOURS",
  "price": "20"
}

###
POST http://localhost:5000/merchants
Content-Type: application/json

{
  "name": "test_name",
  "firstname": "test_firstname",
  "url_validation": "test_url_validation",
  "url_echec": "test_url_echec",
  "kbis": "test_kbis",
  "adresse": "test_adresse",
  "repayment_currency": "test_repayment_currency",
  "verify": false

}

###
GET http://localhost:5000/merchants?name=test_name
Content-Type: application/json

###
GET http://localhost:5000/merchants/1


###
POST http://localhost:5000/credentials
Content-Type: application/json

{
  "client_token": "test_client_token",
  "client_secret": "test_client_secret",
  "MerchantId": 1

}

###
GET http://localhost:5000/credentials?client_token=test_client_token

###
GET http://localhost:5000/credentials/2

###
POST http://localhost:5000/credential_check
Content-Type: application/json

{
  "client_token": "test_client_token",
  "client_secret": "test_client_secret"
}



###
POST http://localhost:5000/login_check
Content-Type: application/json

{
  "email": "superman3-k@hotmail.fr",
  "password": "superman"
}