POST http://localhost:5000/users
Content-Type: application/json

{
  "email": "superman2-k@hotmail.fr",
  "password": "superman",
  "role": "ADMIN"
}

###
GET http://localhost:5000/users?email=superman-k@hotmail.fr

###
GET http://localhost:5000/users/1

###
PUT http://localhost:5000/users/1
Content-Type: application/json

{
  "email": "admin@test.fr",
  "password": "adkjhkjhkjhmklkin",
  "role": "ADMINN"
}

###
POST http://localhost:5000/transactions
Content-Type: application/json

{
  
  "status": "ENCOURS",
  "price": 15.00,
  "MerchantId" : 3
}

###
GET http://localhost:5000/transactions?billing_adress=superman2-k@hotmail.fr

###
GET http://localhost:5000/transactions/1

###
GET http://localhost:5000/transactions/stats?merchantId=1

###
POST http://localhost:5000/merchants
Content-Type: application/json

{
  "name": "test_name",
  "url_validation": "test_url_validation",
  "url_echec": "test_url_echec",
  "kbis": "test_kbis",
  "email": "email@test.fr",
  "adresse": "test_adresse",
  "repayment_currency": "test_repayment_currency",
  "verify": false

}

###
GET http://localhost:5000/merchants?name=test_name
Content-Type: application/json

###
GET http://localhost:5000/merchants/1


###
POST http://localhost:5000/credentials
Content-Type: application/json

{
  "client_token": "test_client_token",
  "client_secret": "test_client_secret"

}

###
GET http://localhost:5000/credentials?client_token=test_client_token

###
GET http://localhost:5000/credentials/1

###
POST http://localhost:5000/credential_check
Content-Type: application/json

{
  "client_token": "test_client_token",
  "client_secret": "test_client_secret"
}



###
POST http://localhost:5000/login_check
Content-Type: application/json

{
  "email": "superman-k@hotmail.fr",
  "password": "superman"
}